https://www.analyticsvidhya.com/blog/2021/08/linear-regression-and-gradient-descent-in-pytorch/

In [41]:
import numpy as np
import torch

In [42]:
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')
# Input (temp, rainfall, humidity)

In [43]:
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')
# Target (apples)

In [44]:
#convert numpy  into tensor
inputs=torch.from_numpy(inputs);
targets=torch.from_numpy(targets);

print(inputs);
print(targets);

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [45]:
from torch.utils.data import TensorDataset
dataset = TensorDataset(inputs, targets)

print(dataset[:])

(tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]), tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]]))


Using Pytorch’s DataLoader class we can convert the dataset into batches of predefined batch size and create batches by picking samples from the dataset randomly.

In [46]:

from torch.utils.data import DataLoader

batch_size=3
train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)


We can access the data from DataLoader as a tuple pair containing input and corresponding targets using a for loop which enables us to load batches directly into a training loop.

In [47]:
# A Batch Sample
for inp,target in train_loader:
    print(inp)
    print(target)
    break

tensor([[ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 87., 134.,  58.]])
tensor([[103.],
        [ 56.],
        [119.]])


In [48]:
#torch.randn generates tensors randomly from a uniform distribution with mean 0 and standard deviation 1.
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.3059,  1.0248, -1.3658],
        [ 1.0789,  2.0404,  0.3302]], requires_grad=True)
tensor([0.5640, 0.1469], requires_grad=True)


In [49]:
# define our Linear Regression model,
def model(X):
    return X @ w.t() + b
    

In [50]:

for x,y in train_loader:
    preds = model(x)
    print("Prediction is :n",preds)
    print("Actual targets is :n",y)
    break

Prediction is :n tensor([[ 24.4442, 293.5832],
        [ 85.2806, 386.5744],
        [ 31.1702, 299.0154]], grad_fn=<AddBackward0>)
Actual targets is :n tensor([[103.],
        [119.],
        [ 81.]])


In [51]:
#def loss function/ Mean Squared Error or L2 loss. 
def mse_loss(predictions, targets):
    difference = predictions - targets
    return torch.sum(difference * difference)/ difference.numel()

In [52]:
for x,y in train_loader:
    preds = model(x)
    print("Prediction is :n",preds)
    print("nActual targets is :n",y)
    print("nLoss is: ",mse_loss(preds, y))
    break

Prediction is :n tensor([[ 24.4442, 293.5832],
        [ 25.2963, 210.1513],
        [ 85.2806, 386.5744]], grad_fn=<AddBackward0>)
nActual targets is :n tensor([[103.],
        [ 22.],
        [119.]])
nLoss is:  tensor(25106.3047, grad_fn=<DivBackward0>)


In [59]:
epochs = 100
for i in range(epochs):
    # Iterate through training dataloader
    for x,y in train_loader:
        # Generate Prediction
        preds = model(x)
        # Get the loss and perform backpropagation
        loss = mse_loss(preds, y)
        loss.backward()
        # Let's update the weights
        with torch.no_grad():
            w -= w.grad *1e-6
            b -= b.grad * 1e-6
            # Set the gradients to zero
            w.grad.zero_()
            b.grad.zero_()
            print(f"Epoch {i}/{epochs}: Loss: {loss}")

Epoch 0/100: Loss: 517.6774291992188
Epoch 0/100: Loss: 43.901004791259766
Epoch 1/100: Loss: 517.280029296875
Epoch 1/100: Loss: 43.814788818359375
Epoch 2/100: Loss: 229.457275390625
Epoch 2/100: Loss: 483.3143310546875
Epoch 3/100: Loss: 516.6277465820312
Epoch 3/100: Loss: 43.26210403442383
Epoch 4/100: Loss: 483.5226745605469
Epoch 4/100: Loss: 94.67074584960938
Epoch 5/100: Loss: 355.5508728027344
Epoch 5/100: Loss: 284.083251953125
Epoch 6/100: Loss: 198.03871154785156
Epoch 6/100: Loss: 520.1531372070312
Epoch 7/100: Loss: 514.6643676757812
Epoch 7/100: Loss: 43.296783447265625
Epoch 8/100: Loss: 481.776611328125
Epoch 8/100: Loss: 94.39044189453125
Epoch 9/100: Loss: 79.82964324951172
Epoch 9/100: Loss: 695.1982421875
Epoch 10/100: Loss: 471.4021301269531
Epoch 10/100: Loss: 106.3453369140625
Epoch 11/100: Loss: 238.2460174560547
Epoch 11/100: Loss: 458.74981689453125
Epoch 12/100: Loss: 479.0358581542969
Epoch 12/100: Loss: 95.46934509277344
Epoch 13/100: Loss: 228.5827026367